{
 "title": "KubernetesPods (Proetheus)",
 "description": "A dashboard to view pod metrics by namespace and pod names.\r\n\r\nUse this Helm chart to launch Grafana into a Kubernetes cluster. It will include this dashboard and many more dashboards to give you visibility into the Kubernetes Cluster. (https://github.com/sekka1/cloud-public/tree/master/kubernetes/pods/grafana-helm)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace" },
   { "name": "pod_name" },
   { "name": "Node", "label": "Node" }
  ]
 },
 "panels": [
  {
   "title": "Nb of rejected requests by GATEWAY",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "istio_requests_total{request_protocol=\"http\", response_code=\"503\", source_app=\"istio-ingressgateway\"}"
    }
   ]
  },
  {
   "title": "CPU & Memory usage (k8s cluster)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\".*\",container_name!=\"POD\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\".*\"}) * 100"
    },
    {
     "expr": "sum (rate (container_memory_max_usage_bytes{id=\"/\",pod_name=~\".*\", kubernetes_io_hostname=~\".*\"}[2m])) / sum (machine_memory_bytes{kubernetes_io_hostname=~\".*\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\".*\",container_name!=\"POD\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\".*\"}) / 1073741824"
    }
   ]
  },
  {
   "title": "Nb of REPLICAS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(istio_requests_total{request_protocol=\"http\", source_app=\"istio-ingressgateway\", destination_service=\"istiocontroller-service.default.svc.cluster.local\", response_code=\"200\"})"
    },
    {
     "expr": "sum(istio_requests_total{request_protocol=\"http\", source_app=\"istio-ingressgateway\", destination_service=\"istiocontroller-service.default.svc.cluster.local\", response_code=\"202\"})"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_memory_max_usage_bytes{id=\"/\",kubernetes_io_hostname=~\".*\",container_name!=\"POD\"}[1m])) / 1073741824"
    }
   ]
  },
  {
   "title": "CPU total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\".*\"})"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(istio_requests_total{source_app=\"istio-ingressgateway\",response_code=~\"200|202|503\", destination_service_name=~\"envoy-service|blur-service\"} )"
    }
   ]
  },
  {
   "title": "percentage of rejected requests",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 12 },
   "targets": [
    {
     "expr": "sum(istio_requests_total{source_app=\"istio-ingressgateway\",response_code=~\"503\", destination_service_name=~\"envoy-service|blur-service\"} ) / sum(istio_requests_total{source_app=\"istio-ingressgateway\",response_code=~\"200|202|503\", destination_service_name=~\"envoy-service|blur-service\"} ) *100"
    },
    {}
   ]
  },
  {
   "title": "Nb of received requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "istio_requests_total{request_protocol=\"http\", source_app=\"istio-ingressgateway\"}"
    }
   ]
  },
  {
   "title": "Average request duration ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": " rate(istio_request_duration_seconds_sum{source_app=\"istio-ingressgateway\", destination_app=\"trip\"}[30s:1s]) \n \n / \n \n rate(istio_request_duration_seconds_count{source_app=\"istio-ingressgateway\", destination_app=\"trip\"}[30s:1s])"
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum( container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\".*\"}) by (kubernetes_io_hostname)"
    },
    {
     "expr": "- sum (container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\".*\"}) by ( kubernetes_io_hostname)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "container_fs_limit_bytes{}" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_allocatable_memory_bytes"
    }
   ]
  },
  {
   "title": "Accepted requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(istio_requests_total{destination_service=\"envoy-service.default.svc.cluster.local\", response_code=\"202\"} )"
    }
   ]
  },
  {
   "title": "Rejected requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(istio_request_bytes_count{destination_service_name=\"envoy-service\",response_code=\"503\"})"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "DMG-image Memory Usage (relative to image's  limits)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "(sum(kube_resourcequota{resourcequota=\"quota-dmgimage\",type=\"hard\", resource=\"limits.memory\", namespace=~\"dmg-image.*\"}) / ( sum(kube_resourcequota{resourcequota=\"quota-image-max\", type=\"hard\", resource=\"limits.memory\"}))) *100"
    }
   ]
  },
  {
   "title": "DMG-image CPU usage (relative to image's  limits)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 47 },
   "targets": [
    {
     "expr": "(sum(kube_resourcequota{resourcequota=\"quota-dmgimage\",type=\"hard\", resource=\"limits.cpu\", namespace=~\"dmg-image.*\"}) / (sum(kube_resourcequota{resourcequota=\"quota-image-max\", type=\"hard\", resource=\"limits.cpu\"}))) *100"
    }
   ]
  },
  {
   "title": "Used  mebibytes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 52 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_resourcequota{resourcequota=\"quota-dmgimage\", namespace=~\"dmg-image.*\", type=\"hard\", resource=\"limits.memory\"})/ 1048576)"
    }
   ]
  },
  {
   "title": "Total  mebibytes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 52 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resourcequota=\"quota-image-max\", type=\"hard\", resource=\"limits.memory\"}) / 1048576 / 2"
    }
   ]
  },
  {
   "title": "Used  cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 52 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_resourcequota{resourcequota=\"quota-dmgimage\", namespace=~\"dmg-image.*\", type=\"hard\", resource=\"limits.cpu\"})*1000)"
    }
   ]
  },
  {
   "title": "Total millicores ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 52 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resourcequota=\"quota-image-max\", type=\"hard\", resource=\"limits.cpu\"})*1000 /2"
    }
   ]
  },
  {
   "title": "Total request (cumulative)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short", "label": "number of requests" }
   ],
   "targets": [
    {
     "expr": "sum(istio_requests_total{request_protocol=\"http\",response_code=\"200\", destination_service_namespace=~\"dmg-image.*\"}) by (destination_service_namespace)"
    }
   ]
  }
 ]
}